AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Ocean Orchestration Role

Parameters:
  RoleName:
    Description: Name of the IAM Role for the deployment
    Type: String
    Default: "GitHubDeployCoreOceanOrchestration"

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:tiki/core-ocean-orchestration:*

  Policy:
    Type: AWS::IAM::RolePolicy
    DependsOn: Role
    Properties:
      RoleName: !Ref RoleName
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
              - s3:PutObject
            Resource:
              - arn:aws:s3:::mytiki-core-ocean-cf-deploy
              - arn:aws:s3:::mytiki-core-ocean-cf-deploy/*
              - arn:aws:s3:::mytiki-athena-query-results-us-east-2
              - arn:aws:s3:::mytiki-athena-query-results-us-east-2/*
              - arn:aws:s3:::mytiki-ocean
              - arn:aws:s3:::mytiki-ocean/*
          - Effect: Allow
            Action: cloudformation:*
            Resource:
              - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/core-ocean-orchestration-cluster/*
              - !Sub arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action:
              - ec2:DescribeVpcs
              - ec2:DescribeSubnets
              - cloudformation:ListStacks
              - ecs:CreateCluster
              - ecs:RegisterTaskDefinition
              - ecs:CreateService
              - route53:CreateHostedZone
              - servicediscovery:CreatePrivateDnsNamespace
              - servicediscovery:TagResource
              - servicediscovery:GetOperation
              - ecr:GetAuthorizationToken
              - ecs:DeregisterTaskDefinition
            Resource: "*"
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:UpdateRole
              - iam:DeleteRole
              - iam:TagRole
              - iam:GetRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PassRole
            Resource:
              - !Sub arn:aws:iam::${AWS::AccountId}:role/core-ocean-orchestration-cluster--TaskExecutionRole-*
              - !Sub arn:aws:iam::${AWS::AccountId}:role/core-ocean-orchestration-cluster-Dagster--AgentRole-*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:TagResource
              - logs:PutRetentionPolicy
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:core-ocean-orchestration-cluster-Dagster-*
          - Effect: Allow
            Action:
              - ecs:DescribeClusters
              - ecs:CreateService
              - ecs:DescribeServices
              - ecs:UpdateService
            Resource:
              - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/Dagster-Cloud-mytiki-*
              - !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service/Dagster-Cloud-mytiki-*
          - Effect: Allow
            Action:
              - servicediscovery:GetNamespace
            Resource: !Sub arn:aws:servicediscovery:${AWS::Region}:${AWS::AccountId}:namespace/*
          - Effect: Allow
            Action:
              - ecr:InitiateLayerUpload
              - ecr:CompleteLayerUpload
              - ecr:UploadLayerPart
              - ecr:PutImage
              - ecr:BatchCheckLayerAvailability
              - ecr:DescribeRepositories
              - ecr:SetRepositoryPolicy
              - ecr:BatchGetImage
            Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/core-ocean
          - Effect: Allow
            Action:
              - glue:GetTable
              - glue:GetDatabases
              - glue:GetDatabase
              - glue:CreateDatabase
              - glue:DeleteTable
              - glue:CreateTable
              - glue:GetPartitions
              - glue:UpdateTable
            Resource:
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*
                - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*
          - Effect: Allow
            Action:
              - athena:StartQueryExecution
              - athena:GetQueryExecution
              - athena:GetQueryResults
            Resource:
              - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/*
          - Effect: Allow
            Action:
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::mytiki-ocean/ocean/dbt_project/*
              - arn:aws:s3:::mytiki-athena-query-results-us-east-2/core-data/dbt_project/*
